---
title: "Massachussetts Education"
author: "Katherine Binney"
date: "10/16/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(tidyverse)
library(leaflet)
library(rgdal)
```

```{r, message = FALSE, results = 'hide'}
colleges <- readOGR("final_project_data/colleges/COLLEGES_PT.shp")
schools <- readOGR("final_project_data/schools/SCHOOLS_PT.shp")

# Have to convert shapefile to R - I have no idea why
schools_transformed <- spTransform(schools, CRS("+proj=longlat +ellps=GRS80"))
colleges_transformed <- spTransform(colleges, CRS("+proj=longlat +ellps=GRS80"))

```

## School locations
```{r}

school_types <- levels(schools_transformed@data$TYPE_DESC)

pal <- colorFactor(palette = "Accent",
                   levels = school_types)

leaflet(schools_transformed) %>% 
  addProviderTiles("CartoDB") %>% 
  addCircleMarkers(radius = 3,
                   opacity = 1,
                   label = ~NAME,
                   color = ~pal(TYPE_DESC)) %>% 
  addLegend(position = "bottomright",
            pal = pal, 
            values = school_types)

```


## College locations
```{r}
college_types = levels(colleges_transformed@data$NCES_TYPE)
college_pal <- colorFactor(palette = "Accent", levels = college_types)

colleges_transformed %>% 
    leaflet() %>% 
    addProviderTiles("CartoDB") %>% 
    addCircles(radius = 4, 
               opacity = 1,
               label = ~COLLEGE,
               color = ~college_pal(NCES_TYPE)) %>% 
  addLegend(position = "bottomright",
            pal = college_pal,
            values = college_types)
  
```

## School District Boundaries